apiVersion: v1
kind: Secret
metadata:
  name: vehicle-sales-main-secrets
  namespace: vehicle-sales
type: Opaque
stringData:
  postgres-password: CHANGE_ME
  connection-string: Host=vehicle-sales-main-db;Port=5432;Database=vehicle_sales_main;Username=main;Password=CHANGE_ME
  service-client-secret: CHANGE_ME
  webhook-secret: CHANGE_ME
